### ISSUE TITLE
Browser not found

### ISSUE THREAD

**Issue by legraphista** [chadparry/kodi-plugin.program.remote.control.browser#1]
Hey there!

I'm getting "Browser not found" message. I was wandering what browser do you recommend installing (OSMC 12.2016, RaspberryPi 3)?

**Comment by chadparry** [comment]
I bought an "Up Board" with an Intel chip just so that I could run a full Chrome version on my home system. If I had a Raspberry Pi 3, I would try Chromium. It looks like the Raspberry Pi ships with Epiphany, so that would be a decent alternative.

I will change the add-on so that it auto-detects Epiphany, and then you won't get a "Browser not found." You can work around this by going to the add-on settings and specifying the path to Epiphany.

However, I don't think you will get satisfactory performance either way. The Raspberry Pi 3 probably doesn't have enough RAM to run Kodi and a browser at the same time. I suspect that you will experience hangs. This add-on is more appropriate for more powerful systems.

**Comment by chadparry** [comment]
I've published a fix in version 1.0.6. You can get it at http://chad.parry.org/software/kodi/, or wait until I update the official add-on repository. The add-on automatically detects Epiphany browsers now. That fixes the "Browser not found" error. The add-on will now show on the configuration page a warning that you have "insufficient memory," because a Raspberry Pi 3 will probably hang when you try this add-on. However, please report back if you are able to get it working reliably, because I would love to make it a supported platform.

**Comment by legraphista** [comment]
I have my OSMC instance installed from their website, and by the looks of it, OSMC doesn't use a window manages, and writes directly to the video buffer. 
Upon trying to start the browser, I see an error message on the screen. Checking the log yields: 
```17:32:13 1243.581543 T:1736332272   ERROR: Exception in thread Thread-2:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/home/osmc/.kodi/addons/plugin.program.remote.control.browser/plugin.py", line 328, in activateWindow
        raise subprocess.CalledProcessError(proc.returncode, cmd, output)
    CalledProcessError: Command '[u'/usr/bin/xdotool', 'search', '--sync', '--onlyvisible', '--pid', '768']' returned non-zero exit status 1
``` 

And then running the command myself: 
```
osmc@Pi:~$ /usr/bin/xdotool search --sync --onlyvisible --pid 768
Error: Can't open display: (null)
Failed creating new xdo instance
```

So unless I install OSMC on top of Raspbian or something with a window manager, I don't think I can really use the plugin :(

But nonetheless, thanks for the effort you've made :D

**Comment by chadparry** [comment]
I don't know for sure, but I found pages that described running a window manager on top of OSMC, (e.g., https://gist.github.com/jesstelford/eded5fe8c2611f332648#window-manager). You could try that. It may not be worth it because of the limited memory, like I said, so I recommend that you try to run a browser and Kodi at the same time (without this add-on and without xdotool) just as a sanity check that this has a chance of working.
